config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount API::Base => '/'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, :controllers => { :passwords => "passwords", :unlocks => "unlocks" }
  get 'reset', to: 'announcements#index', as: 'reset'
  

end

app/models/announcement.rb
# == Schema Information
#
# Table name: announcements
#
#  announcement_type :integer
#  created_at        :datetime         not null
#  id                :integer          not null, primary key
#  message           :text
#  posted_at         :string
#  send_to           :string           default("all")
#  start_time_at     :string           default("00:00:00")
#  updated_at        :datetime         not null
#

class Announcement < ActiveRecord::Base
  #1st assotiations
  
  #2nd scopes

  #3rd enums and others

  enum announcement_type: { calendar: 0, web: 1}
  
  #4th callbacks

  #5th validations
  validates :announcement_type, :message, :posted_at, presence: true
    
   def self.read_by(role)
    if role == 'hr'
      all
    else
      where("send_to iLIKE :role or send_to iLIKE '%all%'", role: "%#{role}%")
    end
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  def index
    @announcements = Announcement.all
    redirect_to "http://hrmis.blgf.grapikomhost.webfactional.com/login"
  end

  # GET /announcements/1
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  def create
    @announcement = Announcement.new(announcement_params)

    if @announcement.save
      redirect_to @announcement, notice: 'Announcement was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /announcements/1
  def update
    if @announcement.update(announcement_params)
      redirect_to @announcement, notice: 'Announcement was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /announcements/1
  def destroy
    @announcement.destroy
    redirect_to announcements_url, notice: 'Announcement was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def announcement_params
      params.require(:announcement).permit(:posted_at, :message, :send_to)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :posted_at %><br>
    <%= f.text_field :posted_at %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :send_to %><br>
    <%= f.number_field :send_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Announcements</h1>

<table>
  <thead>
    <tr>
      <th>Posted at</th>
      <th>Message</th>
      <th>Send to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.posted_at %></td>
        <td><%= announcement.message %></td>
        <td><%= announcement.send_to %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path %>
<%= link_to "Log out", destroy_user_session_path, :method => :delete %>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Posted at:</strong>
  <%= @announcement.posted_at %>
</p>

<p>
  <strong>Message:</strong>
  <%= @announcement.message %>
</p>

<p>
  <strong>Send to:</strong>
  <%= @announcement.send_to %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>